title: Draigercms Docs Site
email: dr_chanmp@disroot.org
author: Drai Tixian
description: Personal Documentation Site
url: "https://draigercms.dpdns.org"
baseurl: "/"

# Social (First three Required)
repo: "https://github.com/draigercms/docs"
github_user: "draigercms"
github_repo: "docs"
github_branch: "main"

# Optional
twitter: jkrebian
linkedin: jkrebian
mastodon: mstdn.plus/jkrebian

# These options are used to configure the locations of your version history when you want to serve versioned documents
version_params:
  version_menu: "Release"
  version_dir: Archive
  tocversion_dir: versions
  versioning: true

  # Disable so older versions cannot be searched
  allow_search: true  

  # Allow these versions to be searched
  search_versions:
    - Previous
  latest: Current
  versions:
    - Current
    - Previous

# Should there be feedback buttons at the bottom of pages?
feedback: true

# Link to a privacy policy in footer, uncomment and define if wanted
privacy: https://draigercms.dpdns.org/privacy

logo: "assets/img/logo/SRCC-square-red.png"
logo_pixels: 34
color: "#30638e"
color: "#8c1515" # primary color for header, buttons

# Build settings
markdown: kramdown

# If you add tags to pages, define this variable to link them to some external search
# If you want to link to tags locally on the site, leave this commented out
# tag_search_endpoint: https://ask.cyberinfrastructure.org/search?q=
tag_color: primary # danger, success, warning, primary, info, secondary

accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:title
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path
  blogs:
    output: true
    permalink: /:collection/:path
  pages:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
